### PR TITLE
Fix issue on mobile devices - onDragEnd

### LINKED ISSUE #1: Problem on mobile devices onDragStop
Hey,
I've found a bug on mobile devices.
I'm using `react-rnd` and storing the image position on my component.. However it was not storing the right positions when I opened my app on mobile devices, it was storing undefined/NaN values, which caused the drag to stop working..

I went deep into your code and I think I found the problem. On the `Draggable`'s `OnDragStop` function, the `coreEvent.position` has invalid positions. And what is causing it is the `getControlPosition` helper from `positionFns.es6`.
I fixed it here (haven't found any problem with my solution) with a simple addition on this line.
```let position = (e.targetTouches && e.targetTouches[0]) || e; ```

Fix:
```
let position = (e.targetTouches && e.targetTouches[0]) ||
    e.changedTouches && e.changedTouches[0] || e;
```

In the `dragStop` event, both lists `e.targetTouches` and `e.touches` are empty, but you can get the position values from `e.changeTouches`, so I just add that small change.

You can see further information about those fields here.
http://stackoverflow.com/questions/7056026/variation-of-e-touches-e-targettouches-and-e-changedtouches

### PR DESCRIPTION
**Pull request by andrejunges**
Fixes #1 

I think this small change is enough to fix the issue mention on #1 .
I had problems to run the tests (panthom problems on macos) and I think some of them are outdated, because my change wouldn't impact on them.

I really need this fix, so it'd be awesome if you can take a look and release a new version if it's good.

Thanks!

### CODE REVIEW

**Comment by bokuweb** [comment]
@andrejunges thanks!!

**Comment by bokuweb** [comment]
updated. please re-install react-rnd.

**Comment by andrejunges** [comment]
Thanks!!

**Comment by andrejunges** [comment]
@bokuweb don't we need to generate the built files?

**Comment by bokuweb** [comment]
ooops.. sory. built it.

**Pull request merged**
